[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pixora_canvas = "Pxra6Kev7iEom8n9zF2fHQKwhu68hL4WnU2qVwB7uS8"

[programs.localnet]
pixora_canvas = "Pxra6Kev7iEom8n9zF2fHQKwhu68hL4WnU2qVwB7uS8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test"
